### ISSUE TITLE
Create pytest-testslide

### ISSUE THREAD

**Issue by fornellas** [facebook/TestSlide#127]
Add TestSlide support for pytest:

- Create the PyPI package.
- Add integration tests to `Makefile` for building, installing and using it.
- Add documentation at `doc/` regarding pytest integration.

StrictMock can be used simply by importing it, just document it.

[Patching tools](https://testslide.readthedocs.io/en/2.2.1/patching/index.html) require special pytest integration, which can be done with  [@pytest.fixture](https://docs.pytest.org/en/latest/reference.html#pytest-fixture). Naming the fixture `testslide` makes sense:

```python
def test_something(testslide):
  testslide.mock_callable(...)
```

but this contrasts with its usage at TestSlide's DSL and Python's Unittest, which access them via `self.mock_callable(...)`, so this is TBD.

The fixture implementation can be copy / pasta from [testslide.TestCase](https://github.com/facebookincubator/TestSlide/blob/master/testslide/__init__.py#L816-L844).

**Comment by fornellas** [comment]
Draft on this branch: https://github.com/facebookincubator/TestSlide/tree/pytest.

**Comment by deathowl** [comment]
@fornellas  i've checked out the pytest branch. Draft seems to be working well, except:
```
-               import pytest_testslide
+               from pytest_testslide import testslide

```
Also i dont get the 
 # FIXME aggregated failures
in the actual module, i've created a case where we expect failure, failure seems fine to me:
```
"    def test_patch_attribute_raises_on_private(testslide):5~5~5~5~                                    130 ↵ deathowl@Therian
>       testslide.patch_attribute(sample_module.SomeClass, "_private_attr", "newval")

test_pass.py:42:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
/home/deathowl/work/TestSlide/pytest-testslide/pytest_testslide.py:43: in patch_attribute
    return testslide_module.patch_attribute.patch_attribute(*args, **kwargs)
/home/deathowl/work/TestSlide/testslide/patch_attribute.py:82: in patch_attribute
    _bail_if_private(attribute, allow_private)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

candidate = '_private_attr', allow_private = False

    def _bail_if_private(candidate: str, allow_private: False):
        if (
            candidate.startswith("_")
            and not allow_private
            and not (candidate.startswith("__") and candidate.endswith("__"))
        ):
            raise ValueError(
>               f"It's disencouraged to patch/mock private interfaces.\n"
                "This would result in way too coupled tests and implementation. "
                "Please consider using patterns like dependency injection instead. "
                "If you really need to do this use the allow_private=True argument."
            )
E           ValueError: It's disencouraged to patch/mock private interfaces.
E           This would result in way too coupled tests and implementation. Please consider using patterns like dependency injection instead. If you really need 

/home/deathowl/work/TestSlide/testslide/lib.py:18: ValueError
=========================== short test summary info ============================
FAILED test_pass.py::test_patch_attribute_raises_on_private - ValueError: It'...
========================= 1 failed, 11 passed in 0.21s =========================
====================================================================================================================================================== warnings 
tests/test_pytest_testslide.py::test_pass
  /home/deathowl/work/TestSlide/.venv/lib/python3.7/site-packages/_pytest/compat.py:333: PytestDeprecationWarning: The TerminalReporter.writer attribute is depr
  See https://docs.pytest.org/en/latest/deprecations.html\#terminalreporter-writer for more information.
    return getattr(object, name, default)

-- Docs: https://docs.pytest.org/en/latest/warnings.html
=================================================================================================================================================== short test s
FAILED pytest-testslide/tests/test_pytest_testslide.py::test_pass - assert '12 passed' in "============================= test session starts ===================
```

**Comment by fornellas** [comment]
> FIXME aggregated failures

IIRC, this has to do with the fact that TestSlide can report multiple failures from a single test execution:

https://testslide.readthedocs.io/en/master/test_runner/index.html#multiple-failures-report

TestSlide uses this class for that:

https://github.com/facebookincubator/TestSlide/blob/b5ae6dae00f3981c3bae1fe8fd940b988804dd42/testslide/__init__.py#L165

and has some code at the runner, to better format this exception, something that pytest will miss.

In retrospect, it would have probably been a better design to have `AggregatedExceptions.__str__` deal with generating a nice combine exception message, and not have testslide runner specific code to deal with it. This would allow pytest to "just work" I bet. This needs checking though, because we have this issue https://github.com/facebookincubator/TestSlide/issues/101, where unittest hides multi-line exceptions...

**Comment by fornellas** [comment]
test_aggregated_exceptions should cover it. But I think it is still only reporting the first exception that surfaces, and not reporting all of them. I think you can put test_aggregated_exceptions code at a regular TestCase, and run testslide on it to get the reference error. As long as pytest matches that, we're gold.
