### ISSUE TITLE
BUG: Leaked task detection triggers for cancelled tasks

### ISSUE THREAD

**Issue by deathowl** [facebook/TestSlide#277]
Leaked tasks detection shouldn't trigger if a task is cancelled.

**Comment by fornellas** [comment]
https://github.com/facebook/TestSlide/pull/263/files
I bet it requires a 1 line change to change "not done" tasks to "any active tasks", which should exclude cancelled.

**Comment by fornellas** [comment]
@deathowl Check if #278 is the same scenario you spotted.
