### ISSUE TITLE
Make Gitlab CI running tests/linting also for pull requests.

### ISSUE THREAD

**Issue by domandinho** [facebook/TestSlide#313]
Currently, for pull requests, there is only a CLA check. 
I saw that there are tests/linting checks for merged code, but no such information for my pull requests.
This CI run for pull requests could help to avoid accidental CI breaks. Currently, I see that on the main branch there are some failed checks.

**Comment by unnati914** [comment]
could i work on this?

**Comment by deathowl** [comment]
already done
